export const B = {
  name: "Medvastr",
  phone: "9920314164",
  email: "medvastr@gmail.com",
  addr: "LL 001, Gagan Shopping Arcade, Gokuldham, Goregaon East, Mumbai – 400063",
  ig: "https://www.instagram.com/medvastr/",
  fb: "https://www.facebook.com/medvastr/",
  li: "https://www.linkedin.com/company/medvastr/",
};

export const COLS = [
  { n: "Navy Blue", h: "#1a2744" },
  { n: "Black", h: "#1a1a1a" },
  { n: "Wine", h: "#7b1c3c" },
  { n: "Forest Green", h: "#1d6e55" },
  { n: "Heather Grey", h: "#9e9e9e" },
  { n: "Maroon", h: "#7a3535" },
  { n: "Ceil Blue", h: "#7b9db3" },
  { n: "Pastel Lilac", h: "#c4a4b8" },
  { n: "Hot Pink", h: "#e8437a" },
  { n: "Olive", h: "#6b7f6b" },
  { n: "Steel Grey", h: "#607d8b" },
  { n: "Mauve", h: "#b58ca8" },
  { n: "Eucalyptus", h: "#7aab8a" },
  { n: "Charcoal", h: "#3a3a3a" },
  { n: "Galaxy Blue", h: "#2c3e7a" },
  { n: "White", h: "#f0f0f0" },
];

export const SIZES = ["XS", "S", "M", "L", "XL", "2XL", "3XL"];

export const cn = (h: string) => COLS.find((c) => c.h === h)?.n || "Default";

export interface Product {
  id: number;
  name: string;
  short: string;
  fab: string | null;
  type: string;
  gen: string;
  price: number;
  origPrice?: number;
  rating: number;
  rev: number;
  badge: string;
  clrs: string[];
  emo: string;
  bg: string;
  desc: string;
  fabD: string;
  stretch: string;
  pockets: number;
  care: string;
  wt: string;
  fit: string;
}

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Men's Classic V-Neck Scrub",
    short: "V-Neck Scrub",
    fab: "Classic",
    type: "scrubs",
    gen: "men",
    price: 1099,
    rating: 4.8,
    rev: 2140,
    badge: "Bestseller",
    clrs: ["#1a2744", "#1a1a1a", "#7b1c3c", "#1d6e55", "#9e9e9e", "#7a3535", "#7b9db3"],
    emo: "🥼",
    bg: "#dde3f0",
    desc: "Our signature V-Neck scrub from premium poly-cotton blend. 5 functional pockets, breathable, holds colour through 200+ washes.",
    fabD: "Classic Poly-Cotton Blend",
    stretch: "N/A",
    pockets: 5,
    care: "Machine Wash Cold 30°C",
    wt: "175 GSM",
    fit: "Regular Fit",
  },
  {
    id: 2,
    name: "Women's Classic V-Neck Scrub",
    short: "V-Neck Scrub",
    fab: "Classic",
    type: "scrubs",
    gen: "women",
    price: 1099,
    rating: 4.8,
    rev: 1820,
    badge: "Bestseller",
    clrs: ["#7b1c3c", "#1a2744", "#1a1a1a", "#c4a4b8", "#e8437a", "#1d6e55", "#9e9e9e", "#7a3535", "#7b9db3", "#7aab8a"],
    emo: "👩‍⚕️",
    bg: "#f0dde4",
    desc: "Slim-fit V-Neck, 5 accessible pockets, moisture-wicking fabric for 12-hour shifts.",
    fabD: "Classic Poly-Cotton Blend",
    stretch: "N/A",
    pockets: 5,
    care: "Machine Wash Cold 30°C",
    wt: "165 GSM",
    fit: "Slim Fit",
  },
  {
    id: 3,
    name: "Men's Mandarin Collar Scrub",
    short: "Mandarin Collar",
    fab: "Classic",
    type: "scrubs",
    gen: "men",
    price: 1299,
    rating: 4.7,
    rev: 890,
    badge: "New",
    clrs: ["#1d6e55", "#1a2744", "#1a1a1a", "#9e9e9e", "#7a3535"],
    emo: "🥼",
    bg: "#ddf0e8",
    desc: "Elegant Mandarin collar. Preferred by surgeons. Anti-wrinkle finish.",
    fabD: "Classic Poly-Cotton Blend",
    stretch: "N/A",
    pockets: 5,
    care: "Machine Wash Cold",
    wt: "175 GSM",
    fit: "Regular Fit",
  },
  {
    id: 4,
    name: "Women's Mandarin Collar Scrub",
    short: "Mandarin Collar",
    fab: "Classic",
    type: "scrubs",
    gen: "women",
    price: 1299,
    rating: 4.7,
    rev: 540,
    badge: "",
    clrs: ["#1a2744", "#1a1a1a", "#7b1c3c", "#9e9e9e", "#1d6e55"],
    emo: "👩‍⚕️",
    bg: "#e5ddf0",
    desc: "Refined Mandarin collar scrub. Professional look for rounds.",
    fabD: "Classic Poly-Cotton Blend",
    stretch: "N/A",
    pockets: 5,
    care: "Machine Wash Cold",
    wt: "165 GSM",
    fit: "Slim Fit",
  },
  {
    id: 5,
    name: "Men's Longsleeve Scrub",
    short: "Longsleeve Scrub",
    fab: "Classic",
    type: "scrubs",
    gen: "men",
    price: 1199,
    rating: 4.6,
    rev: 620,
    badge: "",
    clrs: ["#1a2744", "#1a1a1a", "#7b9db3", "#7b1c3c", "#9e9e9e"],
    emo: "🥼",
    bg: "#dde8f0",
    desc: "Full-sleeve scrub for OT rooms. Anti-microbial treated.",
    fabD: "Classic Poly-Cotton Blend",
    stretch: "N/A",
    pockets: 5,
    care: "Machine Wash Cold",
    wt: "185 GSM",
    fit: "Regular Fit",
  },
  {
    id: 6,
    name: "Women's Longsleeve Scrub",
    short: "Longsleeve Scrub",
    fab: "Classic",
    type: "scrubs",
    gen: "women",
    price: 1199,
    rating: 5.0,
    rev: 430,
    badge: "Bestseller",
    clrs: ["#1a2744", "#1a1a1a", "#7b9db3", "#7b1c3c"],
    emo: "👩‍⚕️",
    bg: "#f0dde8",
    desc: "Long-sleeve tailored scrub. Perfect for OT and ICU.",
    fabD: "Classic Poly-Cotton Blend",
    stretch: "N/A",
    pockets: 5,
    care: "Machine Wash Cold",
    wt: "175 GSM",
    fit: "Slim Fit",
  },
  {
    id: 7,
    name: "Men's ecoflex™ V-Neck Scrub",
    short: "ecoflex™ V-Neck",
    fab: "ecoflex™",
    type: "scrubs",
    gen: "men",
    price: 2399,
    rating: 4.8,
    rev: 1400,
    badge: "Premium",
    clrs: ["#1a2744", "#7b1c3c", "#607d8b", "#1a1a1a", "#1d6e55", "#7aab8a"],
    emo: "🥼",
    bg: "#ddedf5",
    desc: "4-way stretch ecoflex™. Lab-tested 200+ washes. Anti-odour, moisture-wicking.",
    fabD: "ecoflex™ 4-way Stretch",
    stretch: "4-way",
    pockets: 8,
    care: "Machine Wash Warm 40°C",
    wt: "145 GSM",
    fit: "Athletic Fit",
  },
  {
    id: 8,
    name: "Women's ecoflex™ V-Neck Scrub",
    short: "ecoflex™ V-Neck",
    fab: "ecoflex™",
    type: "scrubs",
    gen: "women",
    price: 2399,
    rating: 4.9,
    rev: 1200,
    badge: "Premium",
    clrs: ["#1a2744", "#7b1c3c", "#b58ca8", "#1a1a1a", "#1d6e55", "#2c3e7a", "#e8437a"],
    emo: "👩‍⚕️",
    bg: "#f0e8f5",
    desc: "Women's ecoflex™ 4-way stretch. Ultra-soft, long-shift ready.",
    fabD: "ecoflex™ 4-way Stretch",
    stretch: "4-way",
    pockets: 8,
    care: "Machine Wash Warm 40°C",
    wt: "135 GSM",
    fit: "Athletic Slim",
  },
  {
    id: 9,
    name: "Men's ecoflex™ Jogger Scrub",
    short: "ecoflex™ Jogger",
    fab: "ecoflex™",
    type: "scrubs",
    gen: "men",
    price: 1799,
    rating: 4.7,
    rev: 680,
    badge: "",
    clrs: ["#1a2744", "#1a1a1a", "#607d8b", "#1d6e55"],
    emo: "🥼",
    bg: "#e0eef5",
    desc: "Jogger-style scrub pants. ecoflex™ 2-way stretch.",
    fabD: "ecoflex™ 2-way Stretch",
    stretch: "2-way",
    pockets: 4,
    care: "Machine Wash Warm",
    wt: "160 GSM",
    fit: "Jogger Fit",
  },
  {
    id: 10,
    name: "Women's ecoflex™ Jogger Scrub",
    short: "ecoflex™ Jogger",
    fab: "ecoflex™",
    type: "scrubs",
    gen: "women",
    price: 1799,
    rating: 4.8,
    rev: 520,
    badge: "",
    clrs: ["#1a2744", "#1a1a1a", "#b58ca8", "#e8437a", "#c4a4b8"],
    emo: "👩‍⚕️",
    bg: "#f5e0ee",
    desc: "Jogger-fit scrub pants with tapered silhouette.",
    fabD: "ecoflex™ 2-way Stretch",
    stretch: "2-way",
    pockets: 4,
    care: "Machine Wash Warm",
    wt: "150 GSM",
    fit: "Jogger Slim",
  },
  {
    id: 11,
    name: "6sense All Black Stethoscope",
    short: "6sense Stethoscope",
    fab: "",
    type: "stethoscope",
    gen: "unisex",
    price: 2339,
    origPrice: 2599,
    rating: 4.8,
    rev: 670,
    badge: "10% Off",
    clrs: ["#1a1a1a", "#1a2744", "#7a3535", "#1d6e55", "#e8437a", "#607d8b"],
    emo: "🩺",
    bg: "#f0f0f0",
    desc: "6sense dual-head. 30-day free trial. Brilliant acoustic clarity.",
    fabD: "Stainless Steel + HD Tubing",
    stretch: "N/A",
    pockets: 0,
    care: "Wipe with damp cloth",
    wt: "135g",
    fit: "N/A",
  },
  {
    id: 12,
    name: "6sense Lite Stethoscope",
    short: "6sense Lite",
    fab: "",
    type: "stethoscope",
    gen: "unisex",
    price: 1999,
    rating: 4.8,
    rev: 420,
    badge: "",
    clrs: ["#1a1a1a", "#9e9e9e", "#7a3535", "#1a2744", "#1d6e55", "#e8437a"],
    emo: "🩺",
    bg: "#f5f5f5",
    desc: "Lightweight for students and junior doctors.",
    fabD: "Stainless Steel + Lightweight Tubing",
    stretch: "N/A",
    pockets: 0,
    care: "Wipe with damp cloth",
    wt: "115g",
    fit: "N/A",
  },
  {
    id: 13,
    name: "Men's Chief Lab Coat",
    short: "Chief Lab Coat",
    fab: "Classic",
    type: "labcoat",
    gen: "men",
    price: 1799,
    rating: 4.7,
    rev: 380,
    badge: "",
    clrs: ["#f0f0f0", "#9e9e9e"],
    emo: "🥼",
    bg: "#f8f8f8",
    desc: "Full-length lab coat, 4 deep pockets, embroidery-ready.",
    fabD: "Premium Poly-Viscose",
    stretch: "N/A",
    pockets: 4,
    care: "Machine Wash Cold",
    wt: "195 GSM",
    fit: "Regular Fit",
  },
  {
    id: 14,
    name: "Women's Focus Lab Coat",
    short: "Focus Lab Coat",
    fab: "Classic",
    type: "labcoat",
    gen: "women",
    price: 1699,
    rating: 4.8,
    rev: 290,
    badge: "",
    clrs: ["#f0f0f0", "#9e9e9e"],
    emo: "👩‍⚕️",
    bg: "#f8f8f8",
    desc: "Fitted lab coat with modern silhouette. Chest and side pockets.",
    fabD: "Premium Poly-Viscose",
    stretch: "N/A",
    pockets: 4,
    care: "Machine Wash Cold",
    wt: "185 GSM",
    fit: "Slim Fit",
  },
  {
    id: 15,
    name: "Men's DRIFT Jacket",
    short: "DRIFT Jacket",
    fab: "Tech-Shell",
    type: "jacket",
    gen: "men",
    price: 3499,
    rating: 4.9,
    rev: 215,
    badge: "New Launch",
    clrs: ["#1a2744", "#1a1a1a", "#1d6e55"],
    emo: "🧥",
    bg: "#dde3f0",
    desc: "India's first medical outerwear. Tech-shell + fleece. Water-resistant, 6 pockets.",
    fabD: "Tech-Shell + Fleece Lining",
    stretch: "2-way",
    pockets: 6,
    care: "Machine Wash Cold. No Tumble Dry.",
    wt: "280 GSM",
    fit: "Regular Fit",
  },
  {
    id: 16,
    name: "Women's DRIFT Jacket",
    short: "DRIFT Jacket",
    fab: "Tech-Shell",
    type: "jacket",
    gen: "women",
    price: 3499,
    rating: 4.9,
    rev: 178,
    badge: "New Launch",
    clrs: ["#1a2744", "#1a1a1a", "#7b1c3c", "#c4a4b8"],
    emo: "🧥",
    bg: "#f0dde4",
    desc: "Women's DRIFT Jacket. Anti-distraction outer layer, 6 pockets.",
    fabD: "Tech-Shell + Fleece Lining",
    stretch: "2-way",
    pockets: 6,
    care: "Machine Wash Cold. No Tumble Dry.",
    wt: "265 GSM",
    fit: "Regular Fit",
  },
  {
    id: 17,
    name: "Men's Underscrub T-Shirt",
    short: "Underscrub Tee",
    fab: "Modal",
    type: "underscrub",
    gen: "men",
    price: 649,
    rating: 4.6,
    rev: 920,
    badge: "",
    clrs: ["#1a1a1a", "#f0f0f0", "#9e9e9e", "#1a2744", "#3a3a3a"],
    emo: "👕",
    bg: "#dde3f0",
    desc: "Seamless modal-cotton tee. Lies flat under scrubs.",
    fabD: "Modal-Cotton Blend",
    stretch: "2-way",
    pockets: 0,
    care: "Machine Wash Cold",
    wt: "155 GSM",
    fit: "Slim Fit",
  },
  {
    id: 18,
    name: "Women's Underscrub Top",
    short: "Underscrub Top",
    fab: "Modal",
    type: "underscrub",
    gen: "women",
    price: 599,
    rating: 4.7,
    rev: 760,
    badge: "",
    clrs: ["#1a1a1a", "#f0f0f0", "#9e9e9e", "#1a2744", "#3a3a3a", "#c4a4b8"],
    emo: "👚",
    bg: "#f0dde4",
    desc: "Flattering underscrub top. Long length to prevent ride-up.",
    fabD: "Modal-Cotton Blend",
    stretch: "2-way",
    pockets: 0,
    care: "Machine Wash Cold",
    wt: "145 GSM",
    fit: "Slim Fit",
  },
  {
    id: 19,
    name: "Scrub Cap – Adjustable",
    short: "Scrub Cap",
    fab: "Classic",
    type: "accessories",
    gen: "unisex",
    price: 299,
    rating: 4.6,
    rev: 1340,
    badge: "",
    clrs: ["#1a2744", "#1a1a1a", "#7b1c3c", "#1d6e55", "#9e9e9e", "#7b9db3", "#e8437a"],
    emo: "🧢",
    bg: "#e8f0f8",
    desc: "Bouffant scrub cap with adjustable back tie. One size fits all.",
    fabD: "Classic Poly-Cotton",
    stretch: "N/A",
    pockets: 0,
    care: "Machine Wash Cold",
    wt: "N/A",
    fit: "Adjustable",
  },
  {
    id: 20,
    name: "Women's Hijab – Scrub Compatible",
    short: "Scrub Hijab",
    fab: "Modal",
    type: "accessories",
    gen: "women",
    price: 499,
    rating: 4.9,
    rev: 280,
    badge: "",
    clrs: ["#1a2744", "#1a1a1a", "#9e9e9e", "#c4a4b8", "#1d6e55", "#7b9db3"],
    emo: "🧕",
    bg: "#f0e8f5",
    desc: "Purpose-designed hijab. Stays secure through long shifts.",
    fabD: "Premium Modal",
    stretch: "2-way",
    pockets: 0,
    care: "Hand Wash Cold",
    wt: "N/A",
    fit: "One Size",
  },
];

export const SLIDES = [
  {
    ey: "New Collection 2026",
    h: "Crafted for those who",
    em: " heal",
    p: "Premium medical apparel for 12-hour shifts, complete breathability and professional confidence.",
    c1: "Shop Classic Scrubs",
    c2: "Shop ecoflex™",
    g1: "#0b1420",
    g2: "#12203a",
  },
  {
    ey: "4-Way Stretch Technology",
    h: "Move freely through the",
    em: " long haul",
    p: "ecoflex™ — lab-tested 200+ washes. Zero distraction, maximum performance.",
    c1: "Shop ecoflex™",
    c2: "All Colours",
    g1: "#09201c",
    g2: "#0d3630",
  },
  {
    ey: "New Launch",
    h: "India's first medical",
    em: " outerwear",
    p: "Anti-distraction. Lab tested. Long-shift verified. The DRIFT Jacket by Medvastr.",
    c1: "Shop DRIFT Jacket",
    c2: "Learn More",
    g1: "#14082a",
    g2: "#1e0e40",
  },
];

export const REVIEWS = [
  {
    name: "Dr. Priya Sharma",
    role: "Cardiologist, AIIMS Delhi",
    txt: "The ecoflex scrubs are incredible. 12-hour shifts and these feel as fresh at the end as the start. Game changer.",
    r: 5,
    av: "PS",
  },
  {
    name: "Dr. Rahul Mehta",
    role: "Surgeon, Bombay Hospital",
    txt: "Finally a brand that understands what doctors need. Mandarin collar is my go-to for OT. Exceptional quality.",
    r: 5,
    av: "RM",
  },
  {
    name: "Nurse Anita Rao",
    role: "ICU Head Nurse, Apollo",
    txt: "The pockets are genuinely life-saving. Ordered 5 sets — wearing a new one every day. Highly recommend.",
    r: 5,
    av: "AR",
  },
  {
    name: "Dr. Vikram Singh",
    role: "Orthopaedic Surgeon, Fortis",
    txt: "Ordered 8 sets for my team. Bulk discount was great, delivery super fast. Best investment.",
    r: 5,
    av: "VS",
  },
];

export const PROMOS: Record<string, number> = {
  MEDVASTR10: 0.1,
  FIRSTORDER: 0.15,
  DOCTOR20: 0.2,
  BULK50: 0.5,
};

export const fmt = (n: number) => "₹ " + n.toLocaleString("en-IN");
